# Generated by Django 5.1.2 on 2024-10-30 17:44

import django.core.validators
import django.db.models.deletion
import store.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_orderitem_order_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(choices=[('BG', 'Belgium'), ('CY', 'Cyprus'), ('DK', 'Denmark'), ('FI', 'Finland'), ('FR', 'France'), ('DE', 'Germany'), ('LU', 'Luxembourg'), ('NL', 'Netherlands'), ('SE', 'Sweden')], default='SE', max_length=2),
        ),
        migrations.AddField(
            model_name='address',
            name='zip',
            field=models.CharField(default=78391, max_length=5, validators=[django.core.validators.RegexValidator('^\\d{4,5}$', 'Please enter a valid 4- or 5-digit ZIP code.')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='store.address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='store/images', validators=[store.validators.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['webp'])]),
        ),
    ]
